
#General Options
[general]
	#Enable / Disables the ability to throw the eye of ender to locate the stronghold structure
	#
	#Default: false
	throwEyeOfEnder = true
	#Enable / Disables the ability to use the eye of ender on the end portal frame blocks
	#
	#Default: false
	useEyeOfEnder = true
	#Enable / Disables the ability to activate the nether portal
	#
	#Default: false
	activateNetherPortal = true
	#Provide a comma separated list of blocks in the syntax of mod:block
	#
	#Default: minecraft:obsidian,securitycraft:reinforced_obsidian
	activateNetherPortalBlocks = "minecraft:obsidian,securitycraft:reinforced_obsidian"
	#Enable / Disables logging debug messages
	#
	#Default: false
	logDebug = false

#World Generation
[worldgen]
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: -1
	generateStronghold = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateRuinedPortal = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateBuriedTreasure = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateDesertPyramid = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateEndCity = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateFortress = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateIgloo = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateJungleTemple = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: -1
	generateMineshaft = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateNetherFossil = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateOceanMonument = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateOceanRuin = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: -1
	generateShipwreck = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateSwampHut = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateWoodlandMansion = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateAncientCity = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateBastionRemnant = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateMansion = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generatePillagerOutpost = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateTrailRuins = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateTrialChambers = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateVillageDesert = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateVillagePlains = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateVillageSavanna = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateVillageSnowy = -1
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# Default: 0
	generateVillageTaiga = -1
	# Provide a comma separated list of modded structures in the syntax of mod:structure:value
	#
	# mod is the name of the mod
	# structure is the full structure name, partial name ending with *, or only * for all structures in the mod
	# value is one of the following:
	# -1 = Don't change generation
	# 0 = Disable structure generation
	# 1-999999999 = Limits structure generation to no more than defined number
	#
	# HINT: Use the /locate structure command to determine the mod and structure names
	generateModdedStructure = "ae2:*:-1,apotheosis:0:-1,bettermineshafts:*:-1,biomancy:*:-1,brewery:*:-1,chaoszpack_structures:*:-1,dimdoors:*:-1,echoes_of_the_end__structures_:*:-1,horror_element_mod:*:0,meadow:*:-1,meatstruct:*:-1,neepmeat:*:-1,scguns:*:-1,supplementaries:*:-1,survival_instinct:*:-1,tconstruct:*:-1,underground_village:*:-1,unusualend:*:0"

