
[general]
	#Minimum delay (in seconds)
	#Range: 0 ~ 600
	minDelay = 120
	#Maximum delay (in seconds)
	#Range: 0 ~ 600
	maxDelay = 300
	#Delay before starting fade out when changing biomes (in seconds)
	#Range: 3 ~ 15
	fadeDelay = 3
	#Duration of music fade out (in seconds)
	#Range: 5 ~ 10
	fadeDuration = 5
	#Reset delay on biome switch
	resetDelayOnBiomeSwitch = false
	#Print message when skipping
	printOnSkip = true
	#Enable debug logging (no GUI entry)
	debugLog = false
	#Enable structure songs playing
	enableStructure = true
	#Structure should fade out
	#Allowed Values: NEVER, ON_BIOME_SWITCH
	structureFadeOut = "NEVER"

